-- MySQL Script generated by MySQL Workbench
-- Wed Oct 21 18:08:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema games
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema games
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `games` DEFAULT CHARACTER SET utf8 ;
USE `games` ;

-- -----------------------------------------------------
-- Table `games`.`GamesOwned`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `games`.`GamesOwned` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `player_ID` BIGINT NOT NULL,
  `game_ID` BIGINT NOT NULL,
  `purchase_date` DATE NOT NULL,
  `purchase_price` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `games`.`GamesPlayed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `games`.`GamesPlayed` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `player_ID` BIGINT NOT NULL,
  `game_ID` VARCHAR(45) NOT NULL,
  `time_finished` DATE NULL,
  `score` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `games`.`CreditCard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `games`.`CreditCard` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cc_name` VARCHAR(45) NOT NULL,
  `cc_number` VARCHAR(45) NOT NULL,
  `exp_date` VARCHAR(45) NOT NULL,
  `security_code` INT NOT NULL,
  `player_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `games`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `games`.`Player` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `join_date` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `GamesOwned_id` BIGINT,
  `GamesPlayed_id` BIGINT,
  `GamesPlayed_Game_id` BIGINT,
  `CreditCard_id` BIGINT,
  PRIMARY KEY (`id`),
  INDEX `fk_Player_GamesOwned_idx` (`GamesOwned_id` ASC),
  INDEX `fk_Player_GamesPlayed1_idx` (`GamesPlayed_id` ASC, `GamesPlayed_Game_id` ASC),
  INDEX `fk_Player_CreditCard1_idx` (`CreditCard_id` ASC),
  CONSTRAINT `fk_Player_GamesOwned`
    FOREIGN KEY (`GamesOwned_id`)
    REFERENCES `games`.`GamesOwned` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Player_GamesPlayed1`
    FOREIGN KEY (`GamesPlayed_id`)
    REFERENCES `games`.`GamesPlayed` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Player_CreditCard1`
    FOREIGN KEY (`CreditCard_id`)
    REFERENCES `games`.`CreditCard` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `games`.`Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `games`.`Game` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `release_date` VARCHAR(45) NOT NULL,
  `version` VARCHAR(45) NULL,
  `GamesOwned_id` BIGINT,
  `GamesPlayed_id` BIGINT,
  `GamesPlayed_Game_id` BIGINT,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Game_GamesOwned1`
    FOREIGN KEY (`GamesOwned_id`)
    REFERENCES `games`.`GamesOwned` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_GamesPlayed1`
    FOREIGN KEY (`GamesPlayed_id`)
    REFERENCES `games`.`GamesPlayed` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;